### ISSUE TITLE
Missing function in Openload service code?

### ISSUE THREAD

**Issue by sander1** [Twoure/UnSupportedServices.bundle#1]
Maybe it's me, but looking at the service code for Openload, the function `get_url_redirect_v2` doesn't seem to exist: https://github.com/Twoure/UnSupportedServices.bundle/blob/master/Contents/Service%20Sets/com.plexapp.plugins.openload/URL/Openload/ServiceCode.pys#L86

**Comment by Twoure** [comment]
Current Openload code has changed since then, but does not work so is disabled for now.

**Comment by Twoure** [comment]
Current issue resides within the [aacode](https://github.com/Twoure/UnSupportedServices.bundle/blob/8f582a307d87c27be46754d861ff7afff7a6b53c/Contents/Service%20Sets/com.plexapp.plugins.openload/Shared%20Code/openload.pys#L62), they are adding more functions to obfuscate the decode [number](https://github.com/Twoure/UnSupportedServices.bundle/blob/8f582a307d87c27be46754d861ff7afff7a6b53c/Contents/Service%20Sets/com.plexapp.plugins.openload/Shared%20Code/openload.pys#L85).  I know how to fix it, but haven't had the time yet.

I know some kodi devs stopped trying to do it all in Python, instead they use a JS interpreter (or js2py) to evaluate the js functions to get the final decode number.  I've used these methods before, however the packages like js2py are very large.

**Comment by coder-alpha** [comment]
FYI, https://github.com/coder-alpha/FMoviesPlus.bundle/blob/master/Contents/Services/URL/FMovies/ServiceCode.pys#L215-L266

ported from https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/openload.py

**Comment by Twoure** [comment]
Fixed in https://github.com/Twoure/UnSupportedServices.bundle/commit/fd76f12c3c33f9bc3baba604c37fb616629cd807
