### ISSUE TITLE
need support for videohost1.com and videohost.site for hindimoviesonline plex plugin

### ISSUE THREAD

**Issue by hussamnasir** [Twoure/UnSupportedServices.bundle#2]
your "hindimoviesonline" plex plugin depends on this unsupportedServices bundle . This plugin is missing support for videohost1.com and videohost.site which is used by the hindimoviesonline plugin. Below are the relevant log lines from the hindimoviesonline plugin

2017-02-18 17:37:46,018 (7fa013fff700) : DEBUG (services:603) - No service found for URL 'http://videohost.site/play/NaPqvNpeXgvlILA/'
#64	2017-02-18 17:37:46,022 (7fa013fff700) : DEBUG (services:603) - No service found for URL 'http://videohost1.com/play/pZNwL0qLaEOpgnp/'
#65	2017-02-18 17:37:46,026 (7fa013fff700) : DEBUG (services:603) - No service found for URL 'http://hindimoviesonlines.com/wp-content/uploads/AroundTheWorld.html'
#66	2017-02-18 17:37:46,030 (7fa013fff700) : DEBUG (services:603) - No service found for URL 'http://hindimoviesonlines.com/wp-content/uploads/new.html'
#67	2017-02-18 17:37:46,034 (7fa013fff700) : DEBUG (services:603) - No service found for URL 'http://hindimoviesonlines.com/wp-content/uploads/TrendingNow.html'

**Comment by Twoure** [comment]
Added in https://github.com/Twoure/UnSupportedServices.bundle/commit/9e90c4ee98c42359a88548d9e63e6095b8091995.  ~~Not tested with channel yet.~~

**Comment by Twoure** [comment]
Also fixed with https://github.com/Twoure/HindiMoviesOnline.bundle/commit/bb7fd42854a7afac69f711627a1dcebf656a8ff1 and https://github.com/Twoure/HindiMoviesOnline.bundle/commit/47e07cc11f9065e5e8fe11fa34337540fdddd1f0
