### ISSUE TITLE
Vidzi source currently not working

### ISSUE THREAD

**Issue by stormr2010** [Twoure/UnSupportedServices.bundle#3]
Vidzi source website no longer works on Plex and may require some code changes to reflect changes on to the source website

**Comment by Twoure** [comment]
Fixed in https://github.com/Twoure/UnSupportedServices.bundle/commit/14c773c1d4c24c53cf6ce029f43ca8d7a8cbb3e9

**Comment by Twoure** [comment]
I'm currently not monitoring all 100+ sites that this repo supports. If you find a stream host that is broken or you'd like added, the please create an issue for each.

New stream host issue title should start with `[REQ]`
Example title: `[REQ] Add YouTube.com Support`

**Comment by stormr2010** [comment]
Thanks Twoure will do.

Thanks for all your help
