### ISSUE TITLE
[REQ] Add vidzi.tv Support

### ISSUE THREAD

**Issue by stormr2010** [Twoure/UnSupportedServices.bundle#4]
After Vidzi and a few other sources have been removed from the Plex repo.

Can you please add this source to your code?

**Comment by Twoure** [comment]
Already supported, https://github.com/Twoure/UnSupportedServices.bundle/tree/master/Contents/Service%20Sets/com.plexapp.plugins.vidzi

**Comment by stormr2010** [comment]
Thanks Twoure for the update but the vidzi link sources currently do not work. Even with the updated lmwt channel dev you updated. It displays "cannot play media'

**Comment by stormr2010** [comment]
Apologies it works
