### ISSUE TITLE
Openload.co issue

### ISSUE THREAD

**Issue by drag0nb0x** [Twoure/UnSupportedServices.bundle#8]
Openload.co was working amazing on the roku but as of sunday now starts to load and stops at 13% goes to a screen that says "Loading" then back to the 13% screen again. It does this 2 to 4 times then says the item may not be there anymore. Just wanted you to know

**Comment by Twoure** [comment]
Fixed in https://github.com/Twoure/UnSupportedServices.bundle/commit/a2d73c213f1ac6c878e94c0eebc4020d4dc6b9e5.
